[package]
name = "win32_test"
version = "0.1.0"
authors = ["Kenton Hamaluik <kentonh@gmail.com>"]
edition = "2018"

[dependencies]
winapi = { version = "0.3", features = ["windef", "winuser", "libloaderapi", "wingdi", "windowsx", "errhandlingapi", "commctrl"] }
